---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: full
      state: latest

  - name: install core packages
    apt:
      name: 
        - htop
        - tmux
        - nmap
        - wget
        - git
        - python3-pip
        - nano
        - vim-nox
        - lm-sensors
        - rclone
        - fish
        - curl
      state: latest

  - name: install required docker packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
      state: latest
  
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present 
  
  - name: install docker and docker-compose
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io  
        - docker-compose-plugin
      state: latest
    
  - name: Create Docker home directory
    file:
      path: "/home/ubuntu/docker"
      mode: u=rwx
      state: directory

  - name: Add user account to Docker group
    user:
      name: "ubuntu"
      groups: docker
      append: yes