---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - tmux
        - nmap
        - wget
        - git
        - python3-pip
        - nano
        - vim-nox
        - lm-sensors
        - rclone
        - fish
        - curl
        #- docker