---
- hosts: localhost
  connection: local
  become: true

#SHOULD BE RUN BY A SCRIPT THAT INSTALLS GIT, THEN ANSIBLE

#--- system update + upgrade ---
  tasks:
  - name: apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: full
      state: latest

#--- install core packages ---
  - name: install core packages
    apt:
      name: 
        - htop
        - tmux
        - nmap
        - wget
        - python3-pip
        - nano
        - lm-sensors
        - rclone
        - fish
        - curl
      state: latest

#--- install docker ---
  - name: install required docker packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
      state: latest
  
  - name: add docker gpg apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present 
  
  - name: install docker and docker-compose
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io  
        - docker-compose-plugin
      state: latest
    
  - name: create docker home directory
    file:
      path: "/home/ubuntu/docker"
      mode: 0770
      owner: ubuntu
      group: docker
      state: directory

  - name: add user to docker group
    user:
      name: "ubuntu"
      groups: docker
      append: yes

  # - name: download docker-compose file
  #   git:
  #     repo:
  #     dest:

#--- configure git ---
  - name: set git user
    git_config:
      name: user.name
      scope: global
      value: "Ryan LaLiberty"
    become_user: ubuntu

  - name: set git email
    git_config:
      name: user.email
      scope: global
      value: "rlaliberty@gmail.com"
    become_user: ubuntu

  - name: set git editor
    git_config:
      name: core.editor
      scope: global
      value: nano
    become_user: ubuntu

  #git ssh key

#--- assorted config ---
  - name: create bin for scripts
    file:
      path: "/home/ubuntu/bin"
      mode: 0770
      owner: ubuntu
      group: ubuntu
      state: directory

  # - name: download backup scripts
  #   git:
  #     repo: 
  #     dest: /home/ubuntu/bin/

  # - name: create cronjobs
  #   cron:

  - name: config user nano
    lineinfile:
      path: /home/ubuntu/.nanorc
      line: set linenumbers
      state: present
      create: yes
      backup: yes
    become_user: ubuntu

  - name: config root nano
    lineinfile:
      path: /etc/nanorc
      line: set linenumbers
      state: present
      create: yes
      backup: yes

  - name: set default shell to fish
    user:
      name: ubuntu
      shell: /usr/bin/fish

  - name: create backup hdd mount point
    file:
      path: "/media/backup1"
      mode: 0770
      owner: ubuntu
      group: ubuntu
      state: directory
 
  - name: create plex hdd mount point
    file:
      path: "/media/plex_library"
      mode: 0770
      owner: ubuntu
      group: ubuntu
      state: directory

  - name: create plex hdd mount point
    file:
      path: {{ test }}
      mode: 0770
      owner: ubuntu
      group: ubuntu
      state: directory


#passwordless ssh
#passwordless sudo
#reserve dhcp ip
#mount drives, add to fstab