---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: full
      state: latest

  - name: install core packages
    apt:
      name: 
        - htop
        - tmux
        - nmap
        - wget
        - git
        - python3-pip
        - nano
        - vim-nox
        - lm-sensors
        - rclone
        - fish
        - curl
      state: latest

  - name: install docker and docker-compose
    apt:
      name:
        - 
    

  - name: Create Docker home directory
    file:
      path: "{{ docker_location }}"
      mode: u=rwx
      state: directory

  - name: Add user account to Docker group
    user:
      name: "{{ gkserver_user }}"
      groups: docker
      append: yes